### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by gitlerat** [noahfrederick/vim-noctu#6]
Hi on you readme you wrote that "colors across all software that I use in the terminal", but  how can I use your colourset on my whole terminal apps? Because in the repo files is not even a single color code to find? I do not get it how this works ...
Glad about every help :)
Update: I found this issue https://github.com/noahfrederick/vim-noctu/issues/1 there is a link but the data fields contain a wall of text (ansi code) how to I get this into a Colour Code like #FF0000

**Comment by noahfrederick** [comment]
This is only a Vim color scheme, and it simply maps Vim's highlight groups to the terminal emulator's 16 ANSI colors (so you would configure the colors in your terminal emulator's settings). The value of the colors themselves are up to you. They are not dictated by the Vim scheme provided here.

The screen shot image in the README is just an example. I'm sorry, but I don't have the hex color codes. If you want to use the same colors, you could extract them from the screen shot using GIMP or some other program.

> there is a link but the data fields contain a wall of text

That was a configuration file from MacOS's proprietary Terminal app. I'm not sure how to convert it into something useful offhand.

Hope that clarifies things.
